name: Pyinstaller Packing

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

          pyinstaller --clean mhmp.spec
          mv common dist/mhmp/

      - name: Create archives
        run: 7z a mhmp-${{ github.ref_name }}-win64.7z ./dist/mhmp

      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: development-${{ github.sha }}
          path: mhmp-${{ github.ref_name }}-win64.7z

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: mhmp-${{ github.ref_name }}-win64.7z
